services:
  frontend:
    build: ./frontend
    working_dir: /frontend_app
    volumes:
      - ./frontend:/frontend_app
      - /frontend_app/node_modules
    ports:
      - 5173:5173
    command: npm run dev

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_volume:/var/lib/mysql
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password
  
  backend:
    build: ./backend
    working_dir: /rails
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./backend:/rails
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    depends_on:
      - db

volumes:
  mysql_volume: